import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const Pretendard = localFont({
  src: [
    {
      path: "../fonts/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sans",
  display: "swap",
});

// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`min-h-full flex flex-col ${Pretendard.variable}`} >
        <div className="Wrapper">
          {/* GNB */}
          <header className="Header">
            <ul className="Gnb">
              <li>Home</li>
              <li>Board</li>
              <li>Gallery</li>
            </ul>
          </header>
          <div className="Container">
            {/* LNB */}
            <aside  className="Lnb">
              LNB
            </aside>
            {/* Main */}
            <main className="Main">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
