import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const Pretendard = localFont({
  src: [
    {
      path: "../font/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    }
  ],
  variable:"--font-sans",
});

// import { Geist, Geist_Mono } from "next/font/google";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`min-h-full flex flex-col ${Pretendard.variable}`} >{children}</body>
    </html>
  );
}
